apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-cp
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  sources:
    - repoURL: https://charts.konghq.com
      chart: kong
      targetRevision: 2.37.0
      helm:
        valueFiles:
          - values/kong/values-cp.yaml  # This MUST match the 'ref' below
    - repoURL: https://github.com/NirvanaDogra/DevOps.git
      targetRevision: main
      path: core-mono/Kong/deployment/kong-cp
      ref: values                   # This 'ref' creates the '$values' alias
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true