apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-cp
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 15.5.3
      helm:
        parameters:
          - name: auth.username
            value: kong
          - name: auth.password
            value: kong
          - name: auth.database
            value: kong
          - name: fullnameOverride
            value: kong-ee-database-postgresql
          - name: image.tag
            value: 16.4.0-debian-12-r14
    - repoURL: https://charts.konghq.com
      chart: kong
      targetRevision: 2.37.0
      helm:
        valueFiles:
          - $values/kong/values-cp.yaml  # This MUST match the 'ref' below
    - repoURL: https://github.com/NirvanaDogra/DevOps.git
      targetRevision: main
      path: .
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true